### PR TITLE
Add a Quick-Deploy to Replit button + Readme

### PR DESCRIPTION
**Pull request by IsaacLK**
Added a Quick-Deploy to Replit button + readme
Take away the last 2 sentences of the readme if you approve the pull request :)

### CODE REVIEW

**Comment by ayunami2000** [comment]
I would approve this but I have a replit already for this. Can you modify it so it uses my replit as a base instead? (Or uses my GitHub repo) (can you modify pull requests lmao I don't use GitHub this in depth)

**Comment by IsaacLK** [comment]
Was this repository supposed to be for personal use? Sorry if it was I didn't know.

**Comment by ayunami2000** [comment]
No like, your change says `https://repl.it/badge/github/IsaacLK/eaglercraft-replit-server` which is your fork not mine.

**Comment by IsaacLK** [comment]
Oh yes, my fork just includes the deploy to replit button, to make it easier to use.

**Comment by IsaacLK** [comment]
It goes over to your repository if you accept the pull request. (Just the readme was updated)

**Comment by ayunami2000** [comment]
Ok I'll accept and change as needed if needed. Thanks!

**Comment by IsaacLK** [comment]
Awesome!

**Pull request merged**
